Repository GDSC-SKHU/FM_study, pull requests merged in 2023-05, with the labels that each got.

#2 2장
  2장_이상한_나라의_객체/곽성은.md
Labels: 2장

#3 1장 정리
  1장_협력하는_객체들의_공동체/전유진.md
Labels: 1장

#6 1장 내용 공유 정리
  1장_협력하는_객체들의_공동체/README.md
Labels: 1장

#12 4장 성은
  4장_역할_책임_협력/곽성은.md
Labels: 4장
